const test=require('node:test'),assert=require('node:assert/strict');const M=require('../lib/media.cjs');
function fallbackFetch({reel='221466-05',displayed='00:16:35',ids=['210456270'],oembed={}}={}){return async input=>{const url=String(input);if(url.startsWith('https://footagefarm.com/'))return new Response(`<p><strong>Reel Number</strong>: ${reel}</p><p><strong>Duration</strong>: ${displayed}</p>`,{status:200});if(url.startsWith('https://vimeo.com/footagefarm/videos/search:'))return new Response(`<ol>${ids.map(id=>`<li id="clip_${id}"><a href="/${id}">${reel}</a></li>`).join('')}</ol>`,{status:200});if(url.startsWith('https://vimeo.com/api/oembed.json')){const id=new URL(new URL(url).searchParams.get('url')).pathname.slice(1),data=oembed[id]||{video_id:Number(id),title:reel,author_name:'Footage Farm',author_url:'https://vimeo.com/footagefarm',duration:995};return Response.json(data);}throw new Error(`Unexpected URL ${url}`);};}
test('Footage Farm resolves its best fresh signed MP4 instead of handing restricted Vimeo to yt-dlp',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);global.fetch=async()=>new Response(`<div>480 X 360 / 60MB <a href="https://player.vimeo.com/progressive_redirect/download/7/low.mp4?x=1&amp;y=2">Download</a></div><div>720 X 540 / 170MB <a href="https://player.vimeo.com/progressive_redirect/download/7/high.mp4?x=1&amp;y=2">Download</a></div>`,{status:200});const page='https://footagefarm.com/reel-details/a/b/c',r=await M.resolveMedia(page);assert.equal(r.direct,true);assert.equal(r.referer,page);assert.match(r.url,/high\.mp4\?x=1&y=2/);assert.equal(r.alternates.length,1);});
test('Footage Farm records without a screener become permanent preview-unavailable errors',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);global.fetch=async()=>new Response('<img src="/images/request_preview.svg">',{status:200});await assert.rejects(()=>M.resolveMedia('https://footagefarm.com/reel-details/a/b/missing'),e=>e.code==='PREVIEW_UNAVAILABLE');});
test('private related Vimeo embeds are not mistaken for the requested reel',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);global.fetch=async()=>new Response('<iframe src="https://player.vimeo.com/video/212092934?byline=0"></iframe>',{status:200});await assert.rejects(()=>M.resolveMedia('https://footagefarm.com/reel-details/a/b/private'),e=>e.code==='PREVIEW_UNAVAILABLE');});
test('an exact official Vimeo reel with matching Footage Farm author and duration is a fallback',async()=>{const page='https://footagefarm.com/reel-details/a/b/exact',calls=[],fetchImpl=async(...args)=>{calls.push(String(args[0]));return fallbackFetch({oembed:{'210456270':{video_id:210456270,title:'  221466–05  ',author_name:'Footage Farm',author_url:'https://vimeo.com/footagefarm',duration:997}}})(...args);};const r=await M.resolveMedia(page,undefined,fetchImpl);assert.deepEqual(r,{provider:'footagefarm-vimeo',url:'https://vimeo.com/210456270',referer:page,direct:false,scope:'whole-reel'});assert.ok(calls.includes('https://vimeo.com/footagefarm/videos/search:221466-05/sort:date'));assert.equal(calls.some(url=>url==='https://vimeo.com/footagefarm/videos/sort:date'),false);});
test('progressive resolution returns immediately with a structured lazy Vimeo fallback',async()=>{const page='https://footagefarm.com/reel-details/a/b/structured',calls=[],fetchImpl=async input=>{calls.push(String(input));if(String(input)!==page)throw new Error('Healthy progressive resolution must not query Vimeo');return new Response(`<p><strong>Reel Number</strong>: 221466-05</p><p><strong>Duration</strong>: 00:16:35</p><div>480 X 360 / 60MB <a href="https://player.vimeo.com/progressive_redirect/download/7/low.mp4">Low</a></div><div>720 X 540 / 170MB <a href="https://player.vimeo.com/progressive_redirect/download/7/high.mp4">High</a></div>`,{status:200});};const r=await M.resolveMedia(page,undefined,fetchImpl);assert.match(r.url,/high\.mp4$/);assert.equal(r.direct,true);assert.deepEqual(calls,[page]);assert.equal(r.alternates.length,2);assert.deepEqual(r.alternates.map(v=>[v.provider,v.direct,v.url]),[['footagefarm',true,'https://player.vimeo.com/progressive_redirect/download/7/low.mp4'],['footagefarm-vimeo-lookup',false,page]]);});
test('official Vimeo fallback rejects a duration mismatch beyond two seconds',async()=>{const fetchImpl=fallbackFetch({oembed:{'210456270':{video_id:210456270,title:'221466-05',author_name:'Footage Farm',author_url:'https://vimeo.com/footagefarm',duration:998}}});await assert.rejects(()=>M.resolveMedia('https://footagefarm.com/reel-details/a/b/duration',undefined,fetchImpl),e=>e.code==='PREVIEW_UNAVAILABLE');});
test('official Vimeo fallback rejects ambiguous exact matches',async()=>{const shared=id=>({video_id:Number(id),title:'221466-05',author_name:'Footage Farm',author_url:'https://vimeo.com/footagefarm',duration:995}),fetchImpl=fallbackFetch({ids:['210456270','210456271'],oembed:{'210456270':shared('210456270'),'210456271':shared('210456271')}});await assert.rejects(()=>M.resolveMedia('https://footagefarm.com/reel-details/a/b/ambiguous',undefined,fetchImpl),e=>e.code==='PREVIEW_UNAVAILABLE');});
test('official Vimeo fallback rejects a matching title uploaded outside the Footage Farm profile',async()=>{const fetchImpl=fallbackFetch({oembed:{'210456270':{video_id:210456270,title:'221466-05',author_name:'Footage Farm',author_url:'https://vimeo.com/unrelated-uploader',duration:995}}});await assert.rejects(()=>M.resolveMedia('https://footagefarm.com/reel-details/a/b/wrong-author',undefined,fetchImpl),e=>e.code==='PREVIEW_UNAVAILABLE');});
test('Footage Farm page resolution retries transient network failures before classifying the record',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);let calls=0;global.fetch=async()=>{if(++calls<3)throw new TypeError('fetch failed');return new Response('<a href="https://player.vimeo.com/progressive_redirect/download/7/recovered.mp4">Download</a>',{status:200});};const r=await M.resolveMedia('https://footagefarm.com/reel-details/a/b/recovered');assert.equal(calls,3);assert.match(r.url,/recovered\.mp4/);});
test('signed MP4 download falls back to another advertised quality and reports the rendition used',async t=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-alternate-')),original=global.fetch;t.after(async()=>{global.fetch=original;await fs.rm(folder,{recursive:true,force:true});});global.fetch=async url=>String(url).includes('expired')?new Response('',{status:403}):new Response('VIDEO',{status:200,headers:{'content-length':'5'}});let selected;const file=await M.download({url:'https://cdn.test/expired.mp4',alternates:['https://cdn.test/fresh.mp4'],direct:true,provider:'footagefarm',referer:'https://footagefarm.com/reel-details/a/b/c'},folder,{}, {signal:new AbortController().signal,onProgress:()=>{},onCandidate:url=>{selected=url;}});assert.equal(await fs.readFile(file,'utf8'),'VIDEO');assert.equal(selected,'https://cdn.test/fresh.mp4');});
test('a successful progressive rendition never invokes the lazy official Vimeo lookup',async t=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-progressive-first-'));t.after(()=>fs.rm(folder,{recursive:true,force:true}));let vimeoCalls=0,ytDlpCalls=0,selected;const page='https://footagefarm.com/reel-details/a/b/c',tools={fetch:async url=>{if(String(url).startsWith('https://cdn.test/'))return new Response('VIDEO',{status:200,headers:{'content-length':'5'}});vimeoCalls++;throw new Error('Vimeo must not be queried');},runProcess:async()=>{ytDlpCalls++;throw new Error('Vimeo must not be used');}};const file=await M.download({url:'https://cdn.test/good.mp4',direct:true,provider:'footagefarm',alternates:[{provider:'footagefarm-vimeo-lookup',url:page,referer:page,reel:'221466-05',duration:995,direct:false}]},folder,tools,{signal:new AbortController().signal,onProgress:()=>{},onRendition:value=>{selected=value;}});assert.equal(await fs.readFile(file,'utf8'),'VIDEO');assert.equal(vimeoCalls,0);assert.equal(ytDlpCalls,0);assert.equal(selected.url,'https://cdn.test/good.mp4');assert.equal(selected.alternates[0].provider,'footagefarm-vimeo-lookup');});
test('after every progressive download fails, lazy validation resolves the official Vimeo fallback and uses yt-dlp once',async t=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-progressive-vimeo-')),page='https://footagefarm.com/reel-details/a/b/c',vimeoFetch=fallbackFetch(),searches=[];t.after(()=>fs.rm(folder,{recursive:true,force:true}));let ytDlpCalls=0,selected;const tools={ytdlp:'yt-dlp',ffmpeg:'ffmpeg',getVimeoAuth:()=>({mode:'browser',browser:'edge'}),fetch:async(...args)=>{const url=String(args[0]);if(url.startsWith('https://cdn.test/'))return new Response('',{status:403});searches.push(url);return vimeoFetch(...args);},runProcess:async(_exe,args)=>{ytDlpCalls++;await fs.writeFile(args[args.indexOf('-o')+1].replace('%(ext)s','mp4'),'VIMEO');}};const file=await M.download({url:'https://cdn.test/high.mp4',direct:true,provider:'footagefarm',alternates:[{url:'https://cdn.test/low.mp4',direct:true,provider:'footagefarm'},{provider:'footagefarm-vimeo-lookup',url:page,referer:page,reel:'221466-05',duration:995,direct:false}]},folder,tools,{signal:new AbortController().signal,onProgress:()=>{},onRendition:value=>{selected=value;}});assert.equal(await fs.readFile(file,'utf8'),'VIMEO');assert.equal(ytDlpCalls,1);assert.equal(selected.provider,'footagefarm-vimeo');assert.equal(selected.alternates.length,0);assert.deepEqual(searches.map(url=>new URL(url).pathname),['/footagefarm/videos/search:221466-05/sort:date','/api/oembed.json']);});
test('contact-sheet JPEG output converts limited-range YUV to a full-range JPEG format without resizing',()=>{const filter=M.jpegFullRangeFilter('tile=layout=4x4');assert.equal(filter,'tile=layout=4x4,scale=iw:ih:in_range=auto:out_range=full,format=pix_fmts=yuvj420p');assert.match(filter,/scale=iw:ih:/);});
test('known H.264 corruption is distinguished from unrelated FFmpeg failures',()=>{assert.equal(M.isCorruptMediaError(new Error('Invalid NAL unit size (1703530951 > 19825). Error splitting the input into NAL units.')),true);assert.equal(M.isCorruptMediaError(new Error('Permission denied writing card_000001.jpg')),false);});
test('official Footage Farm Vimeo resolution gives an actionable error when access is not configured',async t=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-vimeo-auth-'));t.after(()=>fs.rm(folder,{recursive:true,force:true}));await assert.rejects(()=>M.download({url:'https://vimeo.com/123456',direct:false,provider:'footagefarm-vimeo'},folder,{getVimeoAuth:()=>({mode:'none'})},{signal:new AbortController().signal,onProgress:()=>{}}),e=>e.code==='VIMEO_AUTH_REQUIRED'&&/Settings/.test(e.message));});
test('lazy official Vimeo identity is reported before missing authentication stops the download',async t=>{
 const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-lazy-auth-')),page='https://footagefarm.com/reel-details/a/b/c';t.after(()=>fs.rm(folder,{recursive:true,force:true}));
 const resolver=fallbackFetch();let verified;
 const tools={getVimeoAuth:()=>({mode:'none'}),fetch:async()=>new Response('',{status:403}),resolverFetch:resolver};
 await assert.rejects(()=>M.download({url:'https://cdn.test/expired.mp4',direct:true,provider:'footagefarm',alternates:[{provider:'footagefarm-vimeo-lookup',url:page,referer:page,reel:'221466-05',duration:995,direct:false}]},folder,tools,{signal:new AbortController().signal,onProgress:()=>{},onResolved:value=>{verified=value;}}),error=>error.code==='VIMEO_AUTH_REQUIRED');
 assert.equal(verified.provider,'footagefarm-vimeo');assert.equal(verified.url,'https://vimeo.com/210456270');assert.equal(verified.referer,page);
});
test('yt-dlp applies configured cookies only to an official Footage Farm Vimeo resolution',async t=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),root=await fs.mkdtemp(path.join(os.tmpdir(),'ff-vimeo-args-')),calls=[];t.after(()=>fs.rm(root,{recursive:true,force:true}));const tools={ytdlp:'yt-dlp',ffmpeg:'ffmpeg',getVimeoAuth:()=>({mode:'browser',browser:'edge',profile:'Profile 2'}),runProcess:async(_exe,args)=>{calls.push(args);const output=args[args.indexOf('-o')+1].replace('%(ext)s','mp4');await fs.writeFile(output,'VIDEO');}};for(const [name,resolved] of [['official',{url:'https://vimeo.com/123456',direct:false,provider:'footagefarm-vimeo'}],['ordinary',{url:'https://example.org/watch/123456',direct:false}]])await M.download(resolved,path.join(root,name),tools,{signal:new AbortController().signal,onProgress:()=>{}});assert.deepEqual(calls[0].slice(calls[0].indexOf('--cookies-from-browser'),calls[0].indexOf('--cookies-from-browser')+2),['--cookies-from-browser','edge:Profile 2']);assert.equal(calls[1].includes('--cookies-from-browser'),false);});
test('lazy metadata resolution uses resolverFetch while video bytes remain direct',async t=>{
 const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'ff-split-fetch-')),page='https://footagefarm.com/reel-details/a/b/c';t.after(()=>fs.rm(folder,{recursive:true,force:true}));
 const directCalls=[],resolverCalls=[],resolver=fallbackFetch();
 const tools={ytdlp:'yt-dlp',ffmpeg:'ffmpeg',getVimeoAuth:()=>({mode:'browser',browser:'edge'}),fetch:async url=>{directCalls.push(String(url));return new Response('',{status:403});},resolverFetch:async(...args)=>{resolverCalls.push(String(args[0]));return resolver(...args);},runProcess:async(_exe,args)=>fs.writeFile(args[args.indexOf('-o')+1].replace('%(ext)s','mp4'),'VIDEO')};
 await M.download({url:'https://cdn.test/high.mp4',direct:true,provider:'footagefarm',alternates:[{provider:'footagefarm-vimeo-lookup',url:page,referer:page,reel:'221466-05',duration:995,direct:false}]},folder,tools,{signal:new AbortController().signal,onProgress:()=>{}});
 assert.deepEqual(directCalls,['https://cdn.test/high.mp4']);assert.deepEqual(resolverCalls.map(url=>new URL(url).pathname),['/footagefarm/videos/search:221466-05/sort:date','/api/oembed.json']);
});
