const fs=require('node:fs/promises');const path=require('node:path');const F=require('./footagefarm.cjs');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function normalize(value,base,origin){try{const u=new URL(value.replace(/&amp;/g,'&'),base);u.hash='';if(!['http:','https:'].includes(u.protocol)||u.origin!==origin||/\.(?:jpg|jpeg|png|gif|svg|css|js|ico|woff2?|ttf|pdf|zip)(?:$|\?)/i.test(u.href))return null;return u.href.replace(/\/$/,'');}catch{return null;}}
function pageLinks(html,base,origin){const out=new Set();for(const m of String(html).matchAll(/href=["']([^"'#]+)["']/gi)){const u=normalize(m[1],base,origin);if(u)out.add(u);}return [...out];}
function titleOf(html,url){const value=String(html).match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||new URL(url).pathname.split('/').filter(Boolean).at(-1)||url;return value.replace(/<[^>]+>|&[^;]+;/g,' ').replace(/\s+/g,' ').trim();}
function containsVideo(html,url){return /<(?:video|source)\b|player\.vimeo\.com|youtube(?:-nocookie)?\.com\/embed|(?:src|href)=["'][^"']+\.(?:mp4|mov|m4v|webm)(?:[?"'])/i.test(html)||/\/(?:video|videos|watch|film|films|reel|reels|reel-details)\b/i.test(new URL(url).pathname)&&/(?:vimeo|youtube|\.mp4|<iframe)/i.test(html);}
function sitemapLinks(xml,base,origin){const out=[];for(const m of String(xml).matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)){const u=normalize(m[1],base,origin);if(u)out.push(u);}return out;}
async function get(url,retries=3){let last;for(let n=0;n<=retries;n++)try{const r=await fetch(url,{headers:{'user-agent':'JewishReels/2.5 (+public website catalog importer)','accept':'text/html,application/xhtml+xml,application/xml'},redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{url:r.url,type:r.headers.get('content-type')||'',text:await r.text()};}catch(e){last=e;if(n<retries)await sleep(300*2**n);}throw new Error(`Could not read ${url}: ${last.message}`);}
async function genericCrawl({startUrl,output,maxPages=50000,concurrency=6,onProgress=()=>{}}){const seed=new URL(startUrl);if(!['http:','https:'].includes(seed.protocol)||seed.username||seed.password)throw new Error('Enter a public HTTP(S) website URL.');const origin=seed.origin,seen=new Set(),queued=new Set(),queue=[],items=new Map();
 const enqueue=u=>{u=normalize(u,seed.href,origin);if(u&&!seen.has(u)&&!queued.has(u)&&seen.size+queued.size<maxPages){queued.add(u);queue.push(u);}};enqueue(seed.href);
 for(const candidate of [`${origin}/sitemap.xml`,`${origin}/sitemap_index.xml`])try{const s=await get(candidate,1);for(const u of sitemapLinks(s.text,s.url,origin))enqueue(u);}catch{}
 let active=0,done=0,reject;await new Promise((resolve,no)=>{reject=no;const pump=()=>{while(active<concurrency&&queue.length){const url=queue.shift();queued.delete(url);if(seen.has(url))continue;seen.add(url);active++;get(url).then(page=>{if(/html|xhtml/i.test(page.type)||/<html/i.test(page.text)){for(const link of pageLinks(page.text,page.url,origin))enqueue(link);if(containsVideo(page.text,page.url))items.set(page.url,{url:page.url,title:titleOf(page.text,page.url),source_page:page.url});}}).catch(()=>{}).finally(()=>{active--;done++;if(done%10===0||(!active&&!queue.length))onProgress({stage:'pages',completed:done,total:done+queue.length,reels:items.size});if(!active&&!queue.length)resolve();else pump();});}if(!active&&!queue.length)resolve();};pump();});
 const rows=[...items.values()].sort((a,b)=>a.url.localeCompare(b.url)),key=seed.hostname.toLowerCase().replace(/^www\./,'').replace(/[^a-z0-9]+/g,'-'),label=seed.hostname.replace(/^www\./,'');await fs.mkdir(path.dirname(output),{recursive:true});await fs.writeFile(output,JSON.stringify({version:1,source:{key,label,homepage:seed.href,crawled_at:new Date().toISOString()},total:rows.length,items:rows},null,2)+'\n');return{file:output,total:rows.length,pages:done,sourceKey:key,label};}
async function crawl(options){const host=new URL(options.startUrl).hostname.toLowerCase().replace(/^www\./,'');if(host==='footagefarm.com'){const r=await F.crawl(options);return{...r,sourceKey:'footagefarm',label:'Footage Farm',pages:r.subthemes+r.themes};}return genericCrawl(options);}
module.exports={normalize,pageLinks,titleOf,containsVideo,sitemapLinks,genericCrawl,crawl};
